language: rust
os:
- linux
- osx
rust:
- stable
cache: cargo
script:
- "./scripts/append-build-no.sh ${TRAVIS_BUILD_NUMBER}"
- cargo build --release --verbose --all
- cargo test --verbose --all
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    mkdir build;
    mv target/release/raws build/raws-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER} ;
  fi
deploy:
  provider: bintray
  file: bintray-descriptor.json
  user: hpcsc
  key:
    secure: 0YyEd30Xn+EYg9wxMJhuyWk9ZDfx1CS/Z9fmAPyhkxzaWnB3jCTb6toV3vIhiBlro6qDeq0CR41DLo3+M8+odrswKHi2H4Aa/v4w82iryYPs/mVIPhimJF3YokMSFcXqV7PD9uTAFp6qO5w0iOjr9W3DeH3DmwsW5w14aXz0GQK5UqEpkwWn0CZJd2CWxQGrTW8hn09s/gAm9UDlM4iYCDLZdzHTzFp8yolNqEF2wsvRWUoBl/OCQlpKN0Nzt2FeIcgwSv9g7vBM6dVJFA3yExtKYGU+KtaqCQ9NIYAlr7iYExg9sTOaI0I+5gNhz761WetXavTyB2dCbpreuPlADJ+cNePuLOe7XxYYbve79DlrBIGV/sVoMZ4gN4TsW5dbV0UQ/TzHP+rtnf1oHNQFqpes//ge4U1Ah993UIB+e/Z8TarQi8fH4Gd86cROyna66CmQgL2xkJN/XRoN3n+rgkljHmzJmnBhJXkJirEtBORazLIk+3v0aiepn+m+DgnaHGTCd5cHGiUHlDkuwzUQzBJGaKvFOcVd3eeQbfCLQKzrWzAHGGBx/ueYlkXgnIEW6+kK/uRVat4RvJYNOqfsZydOy2vyJzUcfx2rF4TmI/IVlzyoKjGC1sIa8cGbLnHbEcA0AJwUmh5PzfstsoXJVjZt1ava5FZbSBaAI5JTIHA=
  skip_cleanup: true
  on:
    branch: master
