language: rust
os:
- linux
- osx
rust:
- stable
cache: cargo
script:
- "./scripts/append-build-no.sh ${TRAVIS_BUILD_NUMBER}"
- cargo build --release --verbose --all
- cargo test --verbose --all
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then mkdir build; mv target/release/raws
  build/raws-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER} ; fi
deploy:
  provider: gcs
  access_key_id: GOOGLA7XHWA7JQJSRMWN3BEZ
  secret_access_key:
    secure: Y0XDGHWWQxsAdPJ/yz1sGqNKxz530bJZgzNXfNXAt/CvEheqFgUyPpLNJXEZ9sq3G/Xz10qI/c6QhV7LLCHcyPsdz7h+X9XDg2uUESt2sClQJsMpIz05t6N2yQUUo2H7duv2Ixk28CL7LfOtyIt0/lSVC9014sOgnGViZxB1dFLliojegmj2E+QyvFhXBFjWK1OwFcEgGbn+OIUw1DTUawgHPc5HVUZlqcPyTlGtLJqVP5ah29C4JUriLgphb+l+mZ3KUp9W4Vj2cQ12qgDd+FpikDz/IKEi6MHtWi0IE0r2rsKMlnnDYJ415AQLWSHg6rfnJvGfrb/dE8sQvURucCt362U86fHZ+8ZaAyY+8zCYpc6BQkB1oTw9np39sYVYYtioXjdXSFgF9j640Y3y+LyQoPAm4fcTxJ8i0HeYHe2f1VnBPBCeCEYrzJZT3iNtyFTjSVGGvhv0qOTXK6Ygm14lgccfnkWNPK7XizlRIr5FmwJbFX2KEaSdm8dVAYOM+CUOQWtzQYOammxPpcIuNvkVHxtIzeoaYbLlkzzjz+b9750VaOnpMlmJlN/lpn5Ncw8FxwzONF8Yr2mb7XxYMAj6hek43GmuOylri8/hAiHNBzs6/2Exy219qFgy1hBkM+HAcySQ3iEXgI2Uvtf1op4LWPkHAa+W5qkN0pHMXxM=
  skip_cleanup: true
  bucket: raws-master
  local-dir: build
  acl: public-read
  on:
    branch: master
