language: rust

os:
- linux
- osx

rust:
- stable

cache: cargo

script:
  - ./scripts/append-build-no.sh ${TRAVIS_BUILD_NUMBER}
  - cargo build --release --verbose --all
  - cargo test --verbose --all

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then mkdir build; mv target/release/raws build/raws-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER} ; fi
deploy:
  - provider: gcs
    access_key_id: "GOOGXSXJIII432RYYGT7DNP5"
    secret_access_key:
      secure: "IqPBYctNlPMAKAn8VjLaq/HzZRNVP8kQ/6+6trvsqA1nO3B525QcKK+1efHOGIKt5K9u9wrvwAM2AC4wto438RoyeWiZxKlZtzHGJRKuxjdN/Q072kU1ndsdOhflLZQuWk5uVWk6EIJnh8vlMqe7e2asK7HEuyY6TC+rbfPjVFix7iKFY9yFD7aOORrG1HpyFHFIXf4mUWudfHqCq4RDrIFRQJd9MeLiVA6GUE0eC0m941lnHdSmQbcda5KYU7lHJta1op/CnRVhswb57ESs0KLVtS+uII3wp/TwYafw1ZGwzb4ekrX+p/glcGdFLXkyXXg8hKkOe2IM3zDWvrEhL10m3VILmLKUd8Wv4JdzWXb1Tgm+yNkhFkqtq+vTRWKP1pXaXW8cZYOpbzJjzsRnnfVeeSlpSzgmAtlSZI7qqcqMV/4BQN62ZEGldHFKZS3Yhcjd+am1CymlKEbvXq07yqOlzP5RC+B3lPCWgJPfKG4Rf3DvrpK4yc1qjCA0Uv24kZDSiLTE84hsNkLfjimOqyZR+6kBtXrXIhBeMWjdTKfVQ8iq12HhA9vORkYsN4XXqQ3y7SHQpP60tcaxAGFQgnFuUiZISRezr8oma7DReN2gNAE6WmuEgTHr7NpKmPd90Fp61Wkw+UKSHE62hTfngRnKICvdcm3sYwP09mjxE/E="
    bucket: "raws-master"
    skip_cleanup: true
    acl: public-read
    local-dir: build
    on:
      branch: master
